name: ArmorPoser
version: '${version}'
main: com.mrbysco.armorposer.ArmorPoserPlugin
api-version: 1.21
author: "Mrbysco"
description: "A paper plugin that allows clients to use Armor Poser to pose armor stands"
website: "https://www.curseforge.com/minecraft/bukkit-plugins/armor-poser-plugin"